### ISSUE TITLE
this is funny lol

### ISSUE THREAD

**Issue by Killaship** [MannySyntax/Faygo-Client-Suroi.io-Hack#1]
deobfuscating the code this tampermonkey script pulls off of gist on github shows a ton of weird javascript with some text-encoded binary stuff mixed in (which disassembles to nothing I know how to/want to read)

regardless, I've heard this is a discord token grabber
so, uh
that's a lot of script kiddies crying to their parents I guess

all in all, cool obfuscation, but it's yet to be seen if this actually does anything useful

4.2 skids out of 10

**Comment by MannySyntax** [comment]
By the way pasting code into a random online deobfuscator is not “deobfuscating” the code. Nice try though.

6.6 skids out of 10

**Comment by Killaship** [comment]
raging script kiddie who thinks he's getting away with shit
3.2 suck my dicks out of 10

**Comment by Killaship** [comment]
L

**Comment by Tacogamerman3** [comment]
> raging script kiddie who thinks he's getting away with shit 3.2 suck my dicks out of 10

This
